allData = {'Edu': {'Dates': '2015 - 2016',
         'DegreeField': 'Front End Development',
         'DegreeType': 'Nanodegree',
         'GPA': '',
         'Honors': '',
         'School': 'Udacity'},
 'Email': 'as;dlkfj',
 'Extra': {'Rec': {'dates': ['jun-july'],
                   'skills': ['counsel kids', 'counsle kids', 'council kids'],
                   'title': 'Counselor'},
           'Sloan Kettering': {'dates': ['july-aug'],
                               'skills': ['never ever',
                                          'eat a salad',
                                          'by yourself'],
                               'title': 'Volunteer'}},
 'Name': 'adlk',
 'Phone': ';alksdfj',
 'Role': 'asldkj',
 'Summary': 'a;sldfkjadlksjaslkdfjal;dsfkjlagjdka',
 'Work': {'Shawmut': {'dates': ['aug-sept'],
                      'skills': ['eat', 'drink', 'be merry'],
                      'title': 'Jr .Mkgtg Publishisher'},
          'Workman': {'dates': ['sept-oct'],
                      'skills': ['live', 'laugh', 'love'],
                      'title': 'Jr. Coordinator'}}}