allData = {'Edu': {'Dates': '2009 - 2013',
         'DegreeField': 'English',
         'DegreeType': 'BS',
         'GPA': '3.646',
         'Honors': 'cum laude',
         'School': 'Boston College'},
 'Email': 'jack@jack.com',
 'Extra': {'Sloan Kettering': {'dates': '',
                               'skills': ['Stuff',
                                          'is ',
                                          'great',
                                          'thats',
                                          'awesome'],
                               'title': 'volunteer'},
           'Stupid Stuff': {'dates': '',
                            'skills': ['laughing', 'is', 'believing'],
                            'title': 'Volunteer'}},
 'Name': 'Jack C M',
 'Phone': '9083493020',
 'Role': 'We Dev',
 'Summary': 'i am great you are swell',
 'Work': {'Shawmut': {'dates': '',
                      'skills': ['loving', 'living', 'caring'],
                      'title': 'Jr Mktg Coord'},
          'Workman': {'dates': '',
                      'skills': ['great', 'stuff', 'jack'],
                      'title': 'Publicity Asst'}}}